- name: Install python
  homebrew: name=python state=present

- name: Install pyenv
  homebrew: name=pyenv state=present
  tags: pyenv

- name: Install pyenv-virtualenv
  homebrew: name=pyenv-virtualenv state=present
  tags: pyenv

# A global `virtualenv` command is needed for prezto's pyenv-virtualenv to work
- name: Install virtualenv
  shell: "python3 -m pip install virtualenv"
  args:
    creates: "/usr/local/bin/virtualenv"
